import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Course } from '~/utils/types';
import Router from 'next/router';
import { fetchCourses } from 'services/apiFetchCourses';
import Image from 'next/image';

const IndexPage: NextPage = () => {
  const [courses, setCourses] = useState<Course[]>([]);

  useEffect(() => {
    void (async () => {
      try {
        const coursesResponse = await fetchCourses();
        setCourses(coursesResponse as Course[]);
      } catch (error: unknown) {
        setCourses([]);
      }
    })();
  }, []);

  const openCourseDetails = (course: Course) =>
    Router.push(
      {
        pathname: `course/${course.id}`,
        query: {
          description: course.description,
          id: course.id,
          name: course.name,
          image: course.image,
        },
      },
      `course/${course.id}`,
      { shallow: true }
    );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-3xl font-semibold p-6">Courses</h1>
        {courses.map(course => {
          return (
            <div
              key={course.id}
              onKeyDown={() => openCourseDetails(course)}
              onClick={() => openCourseDetails(course)}
              className="flex m-2 border border-gray-500 rounded-md p-2 items-center cursor-pointer"
            >
              <Image
                className="rounded-md"
                src={course.image}
                alt="course cover"
                height={150}
                width={150}
              />
              <h2 className="text-xl ml-4 font-medium">{course.name}</h2>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default IndexPage;
